import 'package:flutter/material.dart';
import 'package:speech_to_text/speech_to_text.dart';
import 'package:real_estate_crm_sales/services/api_client.dart';
import 'package:real_estate_crm_sales/screens/leads_screen.dart' show mergeRecognizedText;

class DailyWorkReportScreen extends StatefulWidget { const DailyWorkReportScreen({super.key}); @override State<DailyWorkReportScreen> createState()=>_DailyWorkReportScreenState(); }
class _DailyWorkReportScreenState extends State<DailyWorkReportScreen>{
  final text=TextEditingController();final speech=SpeechToText();String language='bn_BD',message='';bool available=false,listening=false,saving=false;List<Map<String,dynamic>> history=[];
  @override void initState(){super.initState();initSpeech();load();}
  @override void dispose(){speech.stop();text.dispose();super.dispose();}
  Future<void> initSpeech()async{available=await speech.initialize(onStatus:(s){if(mounted)setState(()=>listening=s=='listening');},onError:(e){if(mounted)setState(()=>message='Voice input error: ${e.errorMsg}');});if(mounted)setState((){});}
  Future<void> toggle()async{if(listening){await speech.stop();return;}final base=text.text.trim();await speech.listen(listenOptions:SpeechListenOptions(localeId:language,listenMode:ListenMode.dictation,partialResults:true,cancelOnError:true),onResult:(r){final merged=mergeRecognizedText(base,r.recognizedWords);text.value=TextEditingValue(text:merged,selection:TextSelection.collapsed(offset:merged.length));});}
  Future<void> load()async{try{history=await apiClient.getMyDailyWorkReports();if(mounted)setState((){});}catch(_) {}}
  Future<void> submit()async{if(text.text.trim().isEmpty){setState(()=>message='Please type or dictate today’s work summary.');return;}setState((){saving=true;message='';});try{await apiClient.submitDailyWorkReport(summary:text.text.trim(),inputLanguage:language);if(mounted){setState(()=>message='Daily work report submitted successfully.');await load();}}catch(e){if(mounted)setState(()=>message=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>saving=false);}}
  @override Widget build(BuildContext context)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[Text('Daily Work Report',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('Type or use voice in Bangla or English. Submitting again today updates today’s report.',style:TextStyle(color:Color(0xff64748b))),const SizedBox(height:18),DropdownButtonFormField<String>(value:language,decoration:const InputDecoration(labelText:'Voice language'),items:const [DropdownMenuItem(value:'bn_BD',child:Text('বাংলা')),DropdownMenuItem(value:'en_US',child:Text('English'))],onChanged:listening?null:(v)=>setState(()=>language=v??'bn_BD')),const SizedBox(height:12),TextField(controller:text,minLines:6,maxLines:12,decoration:InputDecoration(labelText:'Today’s work summary',hintText:language=='bn_BD'?'আজকের কাজ লিখুন অথবা মাইক্রোফোনে বলুন':'Type or dictate today’s work',suffixIcon:IconButton(onPressed:available?toggle:initSpeech,icon:Icon(listening?Icons.stop_circle:Icons.mic,color:listening?Colors.red:const Color(0xff0f766e))))),if(message.isNotEmpty)Padding(padding:const EdgeInsets.only(top:10),child:Text(message,style:TextStyle(color:message.contains('successfully')?Colors.green:Colors.red,fontWeight:FontWeight.w700))),const SizedBox(height:14),FilledButton(onPressed:saving?null:submit,child:Text(saving?'Submitting…':'Submit Daily Report')),const SizedBox(height:24),Text('Recent reports',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w800)),...history.take(7).map((x)=>Card(child:ListTile(title:Text(x['workDate']?.toString()??''),subtitle:Text(x['summary']?.toString()??'',maxLines:3,overflow:TextOverflow.ellipsis))))]));
}
